from typing import Optional, Sequence

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.database.database import AsyncSessionLocal
from app.models.DAO.return_dao import ReturnDAO


class ReturnRepository:

    def __init__(self, session: Optional[AsyncSession] = None):
        self._session = session

    async def _get_session(self) -> AsyncSession:
        return self._session or AsyncSessionLocal()

    async def create_return(self, sale_id: int) -> ReturnDAO:
        async with await self._get_session() as session:
            refund = ReturnDAO(sale_id=sale_id)
            session.add(refund)
            await session.commit()
            # Reload instance with DB-generated defaults and load the lines, even though empty, to match the return schema
            await session.refresh(refund, attribute_names=["lines"])
            return refund

    async def get_all_returns(self) -> Sequence[ReturnDAO]:
        async with await self._get_session() as session:
            # Statement needed to load lines attribute
            stmt = (
                select(ReturnDAO)
                .options(selectinload(ReturnDAO.lines))
                .order_by(ReturnDAO.created_at.desc())  # Optional: Sort by newest
            )
            returns = await session.execute(stmt)
            return returns.scalars().all()

    async def get_return_by_id(self, return_id: int) -> Optional[ReturnDAO]:
        async with await self._get_session() as session:
            stmt = (
                select(ReturnDAO)
                .options(selectinload(ReturnDAO.lines))  # <--- FETCH LINES NOW
                .where(ReturnDAO.id == return_id)
            )
            returns = await session.execute(stmt)
            return returns.scalars().first()

    async def delete_return(self, refund: ReturnDAO) -> None:
        # This method assumes the controller has already validated everything.
        async with await self._get_session() as session:
            # We re-attach the object to this session to delete it
            await session.delete(refund)
            await session.commit()

    async def get_returns_by_sale_id(self, sale_id: int) -> Sequence[ReturnDAO]:
        async with await self._get_session() as session:
            stmt = (
                select(ReturnDAO)
                .options(selectinload(ReturnDAO.lines))
                .where(ReturnDAO.sale_id == sale_id)
            )
            returns = await session.execute(stmt)
            return returns.scalars().all()

    async def update_return(self, refund: ReturnDAO) -> ReturnDAO:
        async with await self._get_session() as session:
            # Merge the detached sale object into the current session.
            # This makes the session aware of the changes made outside the session.
            merged_return = await session.merge(refund)
            await session.commit()
            # Refresh the object to get any values generated by the database on update.
            return merged_return
