from typing import Optional, Sequence

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.database.database import AsyncSessionLocal
from app.models.DAO.sale_dao import SaleDAO


class SaleRepository:

    def __init__(self, session: Optional[AsyncSession] = None):
        self._session = session

    async def _get_session(self) -> AsyncSession:
        return self._session or AsyncSessionLocal()

    async def create_sale(self) -> SaleDAO:

        async with await self._get_session() as session:
            sale = SaleDAO()
            session.add(sale)
            await session.commit()
            # Reload instance with DB-generated defaults and load the lines, even though empty, to match the return schema
            await session.refresh(sale, attribute_names=["lines"])
            return sale

    async def get_all_sales(self) -> Sequence[SaleDAO]:
        async with await self._get_session() as session:
            # Statement needed to load lines attribute
            stmt = (
                select(SaleDAO)
                .options(selectinload(SaleDAO.lines))
                .order_by(SaleDAO.created_at.desc())  # Optional: Sort by newest
            )
            sales = await session.execute(stmt)
            return sales.scalars().all()

    async def get_sale_by_id(self, sale_id: int) -> Optional[SaleDAO]:
        async with await self._get_session() as session:
            stmt = (
                select(SaleDAO)
                .options(selectinload(SaleDAO.lines))  # <--- FETCH LINES NOW
                .where(SaleDAO.id == sale_id)
            )
            sales = await session.execute(stmt)
            return sales.scalars().first()

    async def delete_sale(self, sale: SaleDAO) -> None:
        # This method assumes the controller has already validated everything.
        async with await self._get_session() as session:
            # We re-attach the object to this session to delete it
            await session.delete(sale)
            await session.commit()

    async def update_sale(self, sale: SaleDAO) -> SaleDAO:
        async with await self._get_session() as session:
            # Merge the detached sale object into the current session.
            # This makes the session aware of the changes made outside the session.
            merged_sale = await session.merge(sale)
            await session.commit()
            # Refresh the object to get any values generated by the database on update.
            return merged_sale
